sonar.projectKey=cesizen
sonar.projectName=Cesizen (local)
sonar.sourceEncoding=UTF-8

# Sources / tests
sonar.sources=back-cesizen/src,front-cesizen/src
sonar.tests=back-cesizen,front-cesizen
sonar.test.inclusions=**/*.spec.ts

# Exclusions usuelles
sonar.exclusions=**/dist/**,**/node_modules/**,**/*.module.ts,**/environments/**,**/environment*.ts

# TypeScript config (multi-projets)
sonar.typescript.tsconfigPath=back-cesizen/tsconfig.json,front-cesizen/tsconfig.app.json

# Rapports de couverture (LCOV)
sonar.javascript.lcov.reportPaths=back-cesizen/coverage/lcov.info,front-cesizen/coverage/lcov.info
sonar.typescript.lcov.reportPaths=back-cesizen/coverage/lcov.info,front-cesizen/coverage/lcov.info
